version: "3"
services:
  app:
    build: .
    command: "bundle exec puma"
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - postgres
    volumes:
      - .:/home/deploy/app

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
